// Generated by scripts/build-studio-environment.mjs. Do not edit by hand.
export const STUDIO_ENVIRONMENT={
  "width": 512,
  "height": 256,
  "incoming": [
    0.4938752173898702,
    -0.7482664209591097,
    -0.4429273449598173
  ],
  "color": [
    0.9225870276251623,
    1.0156893657490307,
    1.0725341210967392
  ],
  "sourceSpread": [
    0.17960121432150006,
    0.019424689923327895,
    0.1628401982349462
  ],
  "windowFraction": 0.8107974925671884,
  "irradiance": 3.737128394647502
} as const;
